id: ACB0DD9EC
title: 'The Wish-Granting King of Jewels: An Essential Garland of Offerings'
type: translation
pechas:
- IE6E0AA02
- I43C64768
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:09:42.483601
  last_modified_at: 2023-01-04 13:09:42.483608
  collections:
  - Mipham Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  IE6E0AA02/EEB4: 1B73
  I43C64768/DE65: 1B73
